#!/usr/bin/env python3
"""Generate the capability views in docs/specs/ from the approved change specs (policies/artifacts.md §12)."""

import argparse
import os
import sys

sys.dont_write_bytecode = True
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import framework_artifacts as fa  # noqa: E402

SUMMARY_PLACEHOLDER = "N/A — no summary yet. The PM Agent may write one or two sentences here; the generator keeps them."


def existing_summary(path):
    if not os.path.isfile(path):
        return None
    body = fa.section(fa.read(path), "Summary")
    text = fa.strip_comments(body or "").strip()
    return text or None


def render(root, cap):
    path = fa.view_path(root, cap.slug)
    sources = cap.sources
    upstream = ", ".join(f"`{d.path}`" for d in sources)
    out = [
        f"# Capability: `{cap.slug}`",
        "",
        "| Field | Value |",
        "|-------|-------|",
        "| Change | N/A — living view across changes |",
        "| Status | N/A — not authoritative; never approved (`.ai/policies/artifacts.md` §12) |",
        "| Owner | PM Agent — generated by `scripts/capability-views.py`; edit only *Summary* by hand |",
        "| Approver | N/A — each criterion is approved at G2 in its source change |",
        f"| Upstream | {upstream} |",
        "",
        "> **Aggregated view, not the source of truth.** Every criterion below is copied verbatim from an approved "
        "change spec and links to it. When this file and a change spec disagree, the change spec wins: fix the spec "
        "through its own change, then regenerate this file.",
        "",
        "<!-- Generated by scripts/capability-views.py from docs/changes/*/spec.md (Capabilities, Baseline, Supersedes:, Revokes:).",
        "     Regenerate instead of editing; `scripts/capability-views.py check` fails when this file is stale. -->",
        "",
        "## Summary",
        "",
        existing_summary(path) or SUMMARY_PLACEHOLDER,
        "",
        "## Current criteria",
        "",
    ]
    if not cap.current:
        out += ["None — every criterion of this capability has been superseded or revoked.", ""]
    for qid, crit, doc in cap.current:
        title = crit.title or fa.short_title(crit.body)
        req = f" (`{crit.requirement}`)" if crit.requirement else ""
        out += [f"### `{qid}` — {title}", "", f"- **Source:** `{doc.path}`{req}", ""]
        if crit.body.strip():
            out += [crit.body.strip("\n"), ""]
    out += ["## History", ""]
    if cap.history:
        out += ["| Criterion | Replaced by | Change | Date |", "|-----------|-------------|--------|------|"]
        for qid, replaced_by, folder, date, _ in cap.history:
            rb = replaced_by if replaced_by.startswith("Revoked") else f"`{replaced_by}`"
            out.append(f"| `{qid}` | {rb.replace('|', '/')} | `{folder}` | {date} |")
    else:
        out.append("None")
    out += ["", "## Change log", ""]
    for d in sources:
        added = sum(1 for q, _, doc in cap.current if doc.change == d.change)
        superseded = sum(1 for h in cap.history if h[4] == d.change and not h[1].startswith("Revoked"))
        revoked = sum(1 for h in cap.history if h[4] == d.change and h[1].startswith("Revoked"))
        how = "inferred from a later Baseline or Supersedes:" if d.change in cap.inferred else "tagged in Capabilities"
        out.append(f"- {d.approval_date() or '—'} — change {d.folder} ({how}): {added} criteria current; "
                   f"superseded {superseded} and revoked {revoked} earlier criteria")
    return "\n".join(out) + "\n"


def seeds_from(args):
    return {s: list(args.from_change or []) for s in (args.capabilities or [])} if args.from_change else {}


def cmd_build(root, args, check):
    model = fa.capability_model(root, seeds=seeds_from(args))
    wanted = args.capabilities or sorted(model)
    stale = 0
    for slug in wanted:
        if slug not in model:
            print(f"skip   {slug}: no approved criteria tagged with this capability")
            continue
        path = fa.view_path(root, slug)
        text = render(root, model[slug])
        old = fa.read(path) if os.path.isfile(path) else None
        rel = os.path.relpath(path, root)
        if old == text:
            print(f"ok     {rel}")
        elif check:
            stale += 1
            print(f"STALE  {rel}: differs from the change specs; run scripts/capability-views.py build {slug}")
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(text)
            print(f"wrote  {rel}")
        cap = model[slug]
        if cap.inferred:
            print(f"       legacy sources inferred for {slug}: "
                  + ", ".join(cap.inferred) + " — confirm they belong to this capability")
    return 1 if stale else 0


def cmd_baseline(root, args):
    exclude = [args.exclude] if args.exclude else []
    model = fa.capability_model(root, exclude=exclude, seeds=seeds_from(args))
    status = 0
    for slug in args.capabilities:
        print(f"<!-- Baseline candidates for `{slug}`: current criteria from the approved specs. "
              "Keep the rows this change touches and set each Disposition. -->")
        print()
        print("| Criterion | Current behavior (short) | Disposition |")
        print("|-----------|--------------------------|-------------|")
        cap = model.get(slug)
        if not cap or not cap.current:
            print("| N/A — new capability | N/A | N/A |")
            if not args.from_change:
                sys.stderr.write(f"note: no current criteria found for {slug}. If older specs predate the "
                                 "Capabilities row, name them with --from NNNN.\n")
            continue
        for qid, crit, _ in cap.current:
            short = (crit.title or fa.short_title(crit.body)).replace("|", "/")
            print(f"| `{qid}` | {short} | `<Kept · Superseded by AC<n> · Revoked>` |")
        print()
    return status


def main():
    parser = argparse.ArgumentParser(
        description="Generate docs/specs/<capability>.md from the approved change specs (policies/artifacts.md §12).",
        epilog="Exit codes: 0 ok · 1 check found a stale or missing view · 2 usage error")
    sub = parser.add_subparsers(dest="command", required=True)
    for name, text in (("build", "write the views (all capabilities when none is named)"),
                       ("check", "exit 1 when a view differs from what build would write"),
                       ("baseline", "print Baseline rows of the current criteria, for a spec being drafted")):
        p = sub.add_parser(name, help=text)
        p.add_argument("capabilities", nargs="*" if name != "baseline" else "+", metavar="capability")
        p.add_argument("--from", dest="from_change", action="append", metavar="NNNN",
                       help="an older change whose spec predates the Capabilities row and belongs to the named capability")
        if name == "baseline":
            p.add_argument("--exclude", metavar="NNNN", help="leave out this change (the one being drafted)")
    args = parser.parse_args()
    root = fa.repo_root()
    if args.from_change and not args.capabilities:
        parser.error("--from needs a capability name")
    if args.command == "baseline":
        return cmd_baseline(root, args)
    return cmd_build(root, args, check=args.command == "check")


if __name__ == "__main__":
    sys.exit(main())
